services:
  presentation:
    depends_on:
      - rabbitmq
      - postgres
    build:
        context: .
        dockerfile: ./RabbitMQDockerEntityExample.Presentation/Dockerfile
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
  postgres:
    image: postgres:16
    restart: always
    ports:
      - 5433:5432
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=0000
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10